Data encoding 

1. nominal Encoding 
2. label and ordinal encoding 
3. target guided ordinal encoding 



### Nominal/OHE encoding 

One hot encoding also known as nomial encoding is a technique used to represent categorical data as numerical data, which is more suitable for machine learnipng algorithms, in this technique, each category is represented as a binary vector where each bit correspponds to a unique category. For example, if we have a categorical variable "color" wiyh threee possible values (red, greeen , blue) we can represent it on hotcoding encoding as follows:

1. Red: [1,0,0]
2. Green [0,1,0]
3. Blue[0,0,1]

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [4]:
## Create a simple dataframe 

df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'blue', 'red']
})

In [5]:
df.head()

   color
0    red
1   blue
2  green
3   blue
4    red

In [6]:
## Create an instance of oneHotEncoder

encoder = OneHotEncoder()

In [11]:
# Fit and Transform 
encoded = encoder.fit_transform(df[['color']]).toarray() ## alphabetically sorting is done in blue B is  then so one

In [12]:
encoder_df = pd.DataFrame(encoded, columns= encoder.get_feature_names_out())

In [13]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         1.0          0.0        0.0
4         0.0          0.0        1.0

In [17]:
pd.concat([df, encoder_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3   blue         1.0          0.0        0.0
4    red         0.0          0.0        1.0