In [1]:
import pandas as pd 
from sklearn.preprocessing import OneHotEncoder
import seaborn as sns

In [2]:
tips = sns.load_dataset('tips')
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
encoder = OneHotEncoder(sparse_output=False)

In [4]:
encoded = encoder.fit_transform(tips[['sex']])

In [5]:
encoded_df = pd.DataFrame(
    encoded,
    columns= encoder.get_feature_names_out(['sex'])
)

In [6]:
encoded_df

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

In [7]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [8]:
categories = ['sex', 'smoker', 'day', 'time']

In [9]:
encoder = OneHotEncoder(sparse_output= False)

In [10]:
encoded = encoder.fit_transform(tips[categories])

In [11]:
encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(categories)
)

In [12]:
encoded_df

,sex_Female,sex_Male,smoker_No,smoker_Yes,day_Fri,day_Sat,day_Sun,day_Thur,time_Dinner,time_Lunch
0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
2,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...
239,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
240,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
241,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
242,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
243,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [13]:
tips

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [22]:
df = pd.DataFrame({
    'time': tips['time'],
    'total_bill': tips['total_bill']
})

In [24]:
df

       time  total_bill
0    Dinner       16.99
1    Dinner       10.34
2    Dinner       21.01
3    Dinner       23.68
4    Dinner       24.59
..      ...         ...
239  Dinner       29.03
240  Dinner       27.18
241  Dinner       22.67
242  Dinner       17.82
243  Dinner       18.78

[244 rows x 2 columns]

In [25]:
df_mean = df.groupby('time')['total_bill'].mean().to_dict()

C:\Users\Eng\AppData\Local\Temp\ipykernel_19424\2625641642.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_mean = df.groupby('time')['total_bill'].mean().to_dict()

In [32]:
df['total_encode'] = df['time'].map(df_mean)

In [34]:
df

       time  total_bill     encode total_encode
0    Dinner       16.99  20.797159    20.797159
1    Dinner       10.34  20.797159    20.797159
2    Dinner       21.01  20.797159    20.797159
3    Dinner       23.68  20.797159    20.797159
4    Dinner       24.59  20.797159    20.797159
..      ...         ...        ...          ...
239  Dinner       29.03  20.797159    20.797159
240  Dinner       27.18  20.797159    20.797159
241  Dinner       22.67  20.797159    20.797159
242  Dinner       17.82  20.797159    20.797159
243  Dinner       18.78  20.797159    20.797159

[244 rows x 4 columns]