### Target Guided Ordinal Encoding 

It is a technique used to encode categorical variables based on their relationship with target variable. This is useful for when we have a categorical variable with a large number os unique categories, and we want to use this variable as a feature in our ml learning model.

In [3]:
import pandas as pd

df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tookyo','New York', 'Paris'],
    'price': [200,150,300,250,100,320]
})

In [4]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [5]:
df['city_encoded'] = df['city'].map(mean_price)

In [6]:
df

       city  price  city_encoded
0  New York    200         150.0
1    London    150         150.0
2     Paris    300         310.0
3    Tookyo    250         250.0
4  New York    100         150.0
5     Paris    320         310.0

In [7]:
df[['price', 'city_encoded']]

   price  city_encoded
0    200         150.0
1    150         150.0
2    300         310.0
3    250         250.0
4    100         150.0
5    320         310.0

In [8]:
median_price = df.groupby('city')['price'].median().to_dict()

In [9]:
median_price

{'London': 150.0, 'New York': 150.0, 'Paris': 310.0, 'Tookyo': 250.0}

In [10]:
city_encoded2 = df['city'].map(median_price)

In [11]:
city_encoded2

0    150.0
1    150.0
2    310.0
3    250.0
4    150.0
5    310.0
Name: city, dtype: float64