Data Manipulation and analysis are key tasks in any data science or data analysis projects. Pandas provide a wide range of functions for manipulation and analysis, making it easier to clean, transform, and extract insights from data.

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('insta.csv')

# Fetch the first five rows

df.head(5)

# last 5 rows 

df.tail(5)

,post_id,platform,timestamp,lang,text,topic,stance,toxicity,is_campaign_suspected,likes,comments,hashtags_joined,source_url
304,ig_800993,instagram,2025-07-27T18:02:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,8009,1088,#YouthVoices;#Sustainability,https://instagram.com/p/ig_800993
305,ig_800994,instagram,2025-08-09T21:33:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,9237,783,#Innovation;#SkillDevelopment,https://instagram.com/p/ig_800994
306,ig_800995,instagram,2025-08-17T17:52:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,10328,786,#CommunityDevelopment;#FinancialInclusion,https://instagram.com/p/ig_800995
307,ig_800997,instagram,2025-08-24T20:46:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,4060,948,#CivicEngagement;#Innovation,https://instagram.com/p/ig_800997
308,ig_800998,instagram,2025-08-14T17:41:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,8893,990,#Innovation;#FinancialInclusion,https://instagram.com/p/ig_800998

In [8]:
df.describe()

              likes     comments
count    309.000000   309.000000
mean   10200.760518   733.495146
std     5457.905844   429.183638
min       45.000000     1.000000
25%     6058.000000   368.000000
50%    10511.000000   759.000000
75%    14379.000000  1073.000000
max    19988.000000  1499.000000

In [9]:
df.dtypes

post_id                  object
platform                 object
timestamp                object
lang                     object
text                     object
topic                    object
stance                   object
toxicity                 object
is_campaign_suspected      bool
likes                     int64
comments                  int64
hashtags_joined          object
source_url               object
dtype: object

In [ ]:
# Handling missing values 

df.isnull().any(axis=0)

post_id                  False
platform                 False
timestamp                False
lang                     False
text                     False
topic                    False
stance                   False
toxicity                 False
is_campaign_suspected    False
likes                    False
comments                 False
hashtags_joined          False
source_url               False
dtype: bool

In [14]:
df.isnull().any(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
304    False
305    False
306    False
307    False
308    False
Length: 309, dtype: bool

In [ ]:
df.isnull().sum() # this tells kitni values missing hai jaise ost_id me koi missing valuue hai

post_id                  0
platform                 0
timestamp                0
lang                     0
text                     0
topic                    0
stance                   0
toxicity                 0
is_campaign_suspected    0
likes                    0
comments                 0
hashtags_joined          0
source_url               0
dtype: int64

In [ ]:
# agar missing values hai aur hame uski place fill krni hai then we use inbuilt function fillna()

df.fillna(0) # 0 is the by default value

,post_id,platform,timestamp,lang,text,topic,stance,toxicity,is_campaign_suspected,likes,comments,hashtags_joined,source_url
0,ig_800004,instagram,2025-08-07T12:37:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,6761,613,#SkillDevelopment;#Innovation,https://instagram.com/p/ig_800004
1,ig_800007,instagram,2025-08-03T13:10:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,8271,88,#DigitalLiteracy;#CommunityDevelopment,https://instagram.com/p/ig_800007
2,ig_800010,instagram,2025-08-20T15:19:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,985,1296,#StartupEcosystem;#FinancialInclusion,https://instagram.com/p/ig_800010
3,ig_800013,instagram,2025-07-23T12:27:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,6364,1255,#WomenInSTEM;#DigitalLiteracy,https://instagram.com/p/ig_800013
4,ig_800023,instagram,2025-08-01T01:55:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,10700,588,#Sustainability;#PublicHealth,https://instagram.com/p/ig_800023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,ig_800993,instagram,2025-07-27T18:02:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,8009,1088,#YouthVoices;#Sustainability,https://instagram.com/p/ig_800993
305,ig_800994,instagram,2025-08-09T21:33:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,9237,783,#Innovation;#SkillDevelopment,https://instagram.com/p/ig_800994
306,ig_800995,instagram,2025-08-17T17:52:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,10328,786,#CommunityDevelopment;#FinancialInclusion,https://instagram.com/p/ig_800995
307,ig_800997,instagram,2025-08-24T20:46:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,4060,948,#CivicEngagement;#Innovation,https://instagram.com/p/ig_800997
308,ig_800998,instagram,2025-08-14T17:41:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,8893,990,#Innovation;#FinancialInclusion,https://instagram.com/p/ig_800998

In [ ]:
# filling missing value with the mean of the column 

df['likes_fillNA']= df['likes'].fillna(df['likes'].mean())
df

# This code means if there is missing values in the dataset then we made 
# new row name likes_fillNA which include the mean of the likes, so when 
# there is missing values it will fill with the mean of the likes.

,post_id,platform,timestamp,lang,text,topic,stance,toxicity,is_campaign_suspected,likes,comments,hashtags_joined,source_url,likes_fillNA
0,ig_800004,instagram,2025-08-07T12:37:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,6761,613,#SkillDevelopment;#Innovation,https://instagram.com/p/ig_800004,6761
1,ig_800007,instagram,2025-08-03T13:10:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,8271,88,#DigitalLiteracy;#CommunityDevelopment,https://instagram.com/p/ig_800007,8271
2,ig_800010,instagram,2025-08-20T15:19:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,985,1296,#StartupEcosystem;#FinancialInclusion,https://instagram.com/p/ig_800010,985
3,ig_800013,instagram,2025-07-23T12:27:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,6364,1255,#WomenInSTEM;#DigitalLiteracy,https://instagram.com/p/ig_800013,6364
4,ig_800023,instagram,2025-08-01T01:55:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,10700,588,#Sustainability;#PublicHealth,https://instagram.com/p/ig_800023,10700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,ig_800993,instagram,2025-07-27T18:02:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,8009,1088,#YouthVoices;#Sustainability,https://instagram.com/p/ig_800993,8009
305,ig_800994,instagram,2025-08-09T21:33:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,9237,783,#Innovation;#SkillDevelopment,https://instagram.com/p/ig_800994,9237
306,ig_800995,instagram,2025-08-17T17:52:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,10328,786,#CommunityDevelopment;#FinancialInclusion,https://instagram.com/p/ig_800995,10328
307,ig_800997,instagram,2025-08-24T20:46:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,4060,948,#CivicEngagement;#Innovation,https://instagram.com/p/ig_800997,4060
308,ig_800998,instagram,2025-08-14T17:41:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,8893,990,#Innovation;#FinancialInclusion,https://instagram.com/p/ig_800998,8893

In [19]:
df.dtypes

post_id                  object
platform                 object
timestamp                object
lang                     object
text                     object
topic                    object
stance                   object
toxicity                 object
is_campaign_suspected      bool
likes                     int64
comments                  int64
hashtags_joined          object
source_url               object
likes_fillNA              int64
dtype: object

In [21]:
# Renaming column
df= df.rename(columns={'lang':'Language'})
df.head()

,post_id,platform,timestamp,Language,text,topic,stance,toxicity,is_campaign_suspected,likes,comments,hashtags_joined,source_url,likes_fillNA
0,ig_800004,instagram,2025-08-07T12:37:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,6761,613,#SkillDevelopment;#Innovation,https://instagram.com/p/ig_800004,6761
1,ig_800007,instagram,2025-08-03T13:10:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,8271,88,#DigitalLiteracy;#CommunityDevelopment,https://instagram.com/p/ig_800007,8271
2,ig_800010,instagram,2025-08-20T15:19:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,985,1296,#StartupEcosystem;#FinancialInclusion,https://instagram.com/p/ig_800010,985
3,ig_800013,instagram,2025-07-23T12:27:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,6364,1255,#WomenInSTEM;#DigitalLiteracy,https://instagram.com/p/ig_800013,6364
4,ig_800023,instagram,2025-08-01T01:55:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,10700,588,#Sustainability;#PublicHealth,https://instagram.com/p/ig_800023,10700

In [23]:
# Changing DataTypes

df['Value_new']= df['likes'].astype(float)
df.head()

,post_id,platform,timestamp,Language,text,topic,stance,toxicity,is_campaign_suspected,likes,comments,hashtags_joined,source_url,likes_fillNA,Value_new
0,ig_800004,instagram,2025-08-07T12:37:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,6761,613,#SkillDevelopment;#Innovation,https://instagram.com/p/ig_800004,6761,6761.0
1,ig_800007,instagram,2025-08-03T13:10:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,8271,88,#DigitalLiteracy;#CommunityDevelopment,https://instagram.com/p/ig_800007,8271,8271.0
2,ig_800010,instagram,2025-08-20T15:19:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,985,1296,#StartupEcosystem;#FinancialInclusion,https://instagram.com/p/ig_800010,985,985.0
3,ig_800013,instagram,2025-07-23T12:27:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,6364,1255,#WomenInSTEM;#DigitalLiteracy,https://instagram.com/p/ig_800013,6364,6364.0
4,ig_800023,instagram,2025-08-01T01:55:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,10700,588,#Sustainability;#PublicHealth,https://instagram.com/p/ig_800023,10700,10700.0

In [ ]:
# applying funciton to one particular function by usingf apply(function)

df['Dislikes'] = df['likes'].apply(lambda x : x*2)
df.head()

,post_id,platform,timestamp,Language,text,topic,stance,toxicity,is_campaign_suspected,likes,comments,hashtags_joined,source_url,likes_fillNA,Value_new,Dislikes
0,ig_800004,instagram,2025-08-07T12:37:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,6761,613,#SkillDevelopment;#Innovation,https://instagram.com/p/ig_800004,6761,6761.0,13522
1,ig_800007,instagram,2025-08-03T13:10:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,8271,88,#DigitalLiteracy;#CommunityDevelopment,https://instagram.com/p/ig_800007,8271,8271.0,16542
2,ig_800010,instagram,2025-08-20T15:19:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,985,1296,#StartupEcosystem;#FinancialInclusion,https://instagram.com/p/ig_800010,985,985.0,1970
3,ig_800013,instagram,2025-07-23T12:27:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,6364,1255,#WomenInSTEM;#DigitalLiteracy,https://instagram.com/p/ig_800013,6364,6364.0,12728
4,ig_800023,instagram,2025-08-01T01:55:00Z,en,Proud of initiatives driving progress in India...,India,pro,safe,False,10700,588,#Sustainability;#PublicHealth,https://instagram.com/p/ig_800023,10700,10700.0,21400

In [28]:
# Data Aggregatingand Grouping

grouped_mean = df.groupby('post_id')['likes'].mean()
print(grouped_mean)

post_id
ig_800004     6761.0
ig_800007     8271.0
ig_800010      985.0
ig_800013     6364.0
ig_800023    10700.0
              ...
ig_800993     8009.0
ig_800994     9237.0
ig_800995    10328.0
ig_800997     4060.0
ig_800998     8893.0
Name: likes, Length: 309, dtype: float64

In [33]:
grouped_sum = df.groupby(['stance', 'timestamp'])['likes'].sum() # same for mean instaead of sum() place mean()
print(grouped_sum)

stance  timestamp
pro     2025-07-15T06:13:00Z    13905
        2025-07-15T08:26:00Z    17331
        2025-07-15T10:07:00Z    14154
        2025-07-15T10:13:00Z    11920
        2025-07-15T11:07:00Z    17938
                                ...
        2025-08-24T13:09:00Z     5583
        2025-08-24T16:41:00Z    12891
        2025-08-24T17:17:00Z    10431
        2025-08-24T17:27:00Z    13910
        2025-08-24T20:46:00Z     4060
Name: likes, Length: 308, dtype: int64

In [35]:
## aggregate mulltiple function

grouped_agg = df.groupby('likes')['comments'].agg(['mean', 'sum', 'count'])
print(grouped_agg)

         mean   sum  count
likes
45      764.0   764      1
61      855.0   855      1
265     748.0   748      1
342     403.0   403      1
409     382.0   382      1
...       ...   ...    ...
19790   832.0   832      1
19794   904.0   904      1
19916    27.0    27      1
19947  1370.0  1370      1
19988  1115.0  1115      1

[308 rows x 3 columns]

In [36]:
# merging and joining DataFrames 
# create smapale dataframes 
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value1':[10,20,30]})

In [38]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [39]:
df2

  Key  Value1
0   A      10
1   B      20
2   D      30

In [ ]:
# merge DataFrame on the 'key colums'

pd.merge(df1,df2,on="Key",how="inner") # hame on= mtlb kon sa column lena hai aur how = "inner" is liye lia hai taaki hame pura mile

  Key  Value1_x  Value1_y
0   A         1        10
1   B         2        20

In [41]:
# merging using outer join

pd.merge(df1,df2,on="Key",how="outer")

  Key  Value1_x  Value1_y
0   A       1.0      10.0
1   B       2.0      20.0
2   C       3.0       NaN
3   D       NaN      30.0

In [ ]:
pd.merge(df1,df2,on="Key",how="left") # left means df1 is more priotized 29

  Key  Value1_x  Value1_y
0   A         1      10.0
1   B         2      20.0
2   C         3       NaN

In [ ]:
pd.merge(df1,df2,on="Key",how="right") # right side df2 is given more priority

  Key  Value1_x  Value1_y
0   A       1.0        10
1   B       2.0        20
2   D       NaN        30