##### Pandas- DataFrame and Series

Pandas is a powerful data manipulation liberary in python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A series is one dimensional array like object, while a DataFrame is a 2D, size- mutable and potentially hetrogeneous tabular data structure with labelled axes (rows & columns)

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\eng\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\eng\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\eng\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\eng\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\eng\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\eng\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

A Pandas Series is a 1D array like object that can hold any data  type. It is similar to a column in a table

In [5]:
# Series 

data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
## creating series from dictinary elements
data= {'a':1,'b':2,'c':3}
series_dict = pd.Series(data)
print(series_dict) # here a b c are the index and 1 2 3 are the vlaues

a    1
b    2
c    3
dtype: int64

In [12]:
data = [1,3,45]
index = ['a','b','c']
pd.Series(data, index= index)

a     1
b     3
c    45
dtype: int64

In [40]:
# DataFrame 
## create a DataFrame from a dictionary of list

data = {
    'Name': ['Alice', 'John', 'Charle'],
    'Age': [25,52,45],
    'City': ['Banglore', 'NewYork', 'Chicago']
}
df= pd.DataFrame(data)
print(df)

     Name  Age      City
0   Alice   25  Banglore
1    John   52   NewYork
2  Charle   45   Chicago

In [16]:
import numpy as np
np.array(df)

array([['Alice', 25, 'Banglore'],
       ['John', 52, 'NewYork'],
       ['Charle', 45, 'Chicago']], dtype=object)

In [21]:
Data= [
    {'Name': 'Alice', 'Age': 25, "city": 'Banglore'},
    {'Name': 'Valice', 'Age': 15, "city": 'Manglore'},
    {'Name': 'Malice', 'Age': 35, "city": 'Aanglore'},
    {'Name': 'Lice',  'Age': 25, "city": 'Qanglore'},
    {'Name': 'Olice', 'Age': 75, "city": 'Wanglore'},
    {'Name': 'Plice', 'Age': 45, "city": 'Uanglore'},
    {'Name': 'Ylice', 'Age': 85, "city": 'Oanglore'},
    {'Name': 'Aice', 'Age': 20, "city": 'Panglore'},
]

df = pd.DataFrame(Data)
print(df)

     Name  Age      city
0   Alice   25  Banglore
1  Valice   15  Manglore
2  Malice   35  Aanglore
3    Lice   25  Qanglore
4   Olice   75  Wanglore
5   Plice   45  Uanglore
6   Ylice   85  Oanglore
7    Aice   20  Panglore

In [26]:
import os
print(os.getcwd())

d:\ML\Data Analysis with Python

In [32]:
df = pd.read_csv('insta.csv') 
print(df.head(5))

     post_id   platform             timestamp lang  \
0  ig_800004  instagram  2025-08-07T12:37:00Z   en
1  ig_800007  instagram  2025-08-03T13:10:00Z   en
2  ig_800010  instagram  2025-08-20T15:19:00Z   en
3  ig_800013  instagram  2025-07-23T12:27:00Z   en
4  ig_800023  instagram  2025-08-01T01:55:00Z   en

                                                text  topic stance toxicity  \
0  Proud of initiatives driving progress in India...  India    pro     safe
1  Proud of initiatives driving progress in India...  India    pro     safe
2  Proud of initiatives driving progress in India...  India    pro     safe
3  Proud of initiatives driving progress in India...  India    pro     safe
4  Proud of initiatives driving progress in India...  India    pro     safe

   is_campaign_suspected  likes  comments  \
0                  False   6761       613
1                  False   8271        88
2                  False    985      1296
3                  False   6364      1255
4                  False  10700       588

                          hashtags_joined                         source_url
0           #SkillDevelopment;#Innovation  https://instagram.com/p/ig_800004
1  #DigitalLiteracy;#CommunityDevelopment  https://instagram.com/p/ig_800007
2   #StartupEcosystem;#FinancialInclusion  https://instagram.com/p/ig_800010
3           #WomenInSTEM;#DigitalLiteracy  https://instagram.com/p/ig_800013
4           #Sustainability;#PublicHealth  https://instagram.com/p/ig_800023

In [37]:
from IPython.display import display

df = pd.read_csv('insta.csv')

pd.set_option('display.max_colwidth', None)
display(df)

,post_id,platform,timestamp,lang,text,topic,stance,toxicity,is_campaign_suspected,likes,comments,hashtags_joined,source_url
0,ig_800004,instagram,2025-08-07T12:37:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,6761,613,#SkillDevelopment;#Innovation,https://instagram.com/p/ig_800004
1,ig_800007,instagram,2025-08-03T13:10:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,8271,88,#DigitalLiteracy;#CommunityDevelopment,https://instagram.com/p/ig_800007
2,ig_800010,instagram,2025-08-20T15:19:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,985,1296,#StartupEcosystem;#FinancialInclusion,https://instagram.com/p/ig_800010
3,ig_800013,instagram,2025-07-23T12:27:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,6364,1255,#WomenInSTEM;#DigitalLiteracy,https://instagram.com/p/ig_800013
4,ig_800023,instagram,2025-08-01T01:55:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,10700,588,#Sustainability;#PublicHealth,https://instagram.com/p/ig_800023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,ig_800993,instagram,2025-07-27T18:02:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,8009,1088,#YouthVoices;#Sustainability,https://instagram.com/p/ig_800993
305,ig_800994,instagram,2025-08-09T21:33:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,9237,783,#Innovation;#SkillDevelopment,https://instagram.com/p/ig_800994
306,ig_800995,instagram,2025-08-17T17:52:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,10328,786,#CommunityDevelopment;#FinancialInclusion,https://instagram.com/p/ig_800995
307,ig_800997,instagram,2025-08-24T20:46:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,4060,948,#CivicEngagement;#Innovation,https://instagram.com/p/ig_800997
308,ig_800998,instagram,2025-08-14T17:41:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,8893,990,#Innovation;#FinancialInclusion,https://instagram.com/p/ig_800998

In [41]:
## accessing data from DataFrame
df

     Name  Age      City
0   Alice   25  Banglore
1    John   52   NewYork
2  Charle   45   Chicago

In [ ]:
df['Name'] # if we pick up one column it is series

0     Alice
1      John
2    Charle
Name: Name, dtype: object

In [ ]:
df.loc[0] # row location

Name       Alice
Age           25
City    Banglore
Name: 0, dtype: object

In [46]:
# column loc
df.iloc[0][0]

C:\Users\Eng\AppData\Local\Temp\ipykernel_19632\2245630359.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Alice'

In [49]:
df

     Name  Age      City
0   Alice   25  Banglore
1    John   52   NewYork
2  Charle   45   Chicago

In [51]:
#Accesssing a specified element 
df.at[2,'Age']

np.int64(45)

In [53]:
df.at[2,'Name']

'Charle'

In [54]:
## Accessing specified element using iat
df.iat[2,2]

'Chicago'

In [55]:
## data Manipulation with DataFrame

df

     Name  Age      City
0   Alice   25  Banglore
1    John   52   NewYork
2  Charle   45   Chicago

In [68]:
df['Salary']= [50000,60000,70000]
df

     Name  Age      City  Salary
0   Alice   25  Banglore   50000
1    John   52   NewYork   60000
2  Charle   45   Chicago   70000

In [69]:
#Remove column 
df.drop('Salary', axis=1) # without axix = 1 it will give error

     Name  Age      City
0   Alice   25  Banglore
1    John   52   NewYork
2  Charle   45   Chicago

In [63]:
df # drop function is not permanet as it is temporary

     Name  Age      City  Salary
0   Alice   25  Banglore   50000
1    John   52   NewYork   60000
2  Charle   45   Chicago   70000

In [70]:

#Remove column 
df.drop('Salary', axis=1, inplace= True)
df

     Name  Age      City
0   Alice   25  Banglore
1    John   52   NewYork
2  Charle   45   Chicago

In [77]:
df.drop('age', axis=1, inplace=True)

In [78]:
## Add age toh the column 

df['Age']= df['Age']+1
df

     Name  Age      City
0   Alice   29  Banglore
1    John   56   NewYork
2  Charle   49   Chicago

In [79]:
from IPython.display import display

df = pd.read_csv('insta.csv')

pd.set_option('display.max_colwidth', None)
display(df)

,post_id,platform,timestamp,lang,text,topic,stance,toxicity,is_campaign_suspected,likes,comments,hashtags_joined,source_url
0,ig_800004,instagram,2025-08-07T12:37:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,6761,613,#SkillDevelopment;#Innovation,https://instagram.com/p/ig_800004
1,ig_800007,instagram,2025-08-03T13:10:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,8271,88,#DigitalLiteracy;#CommunityDevelopment,https://instagram.com/p/ig_800007
2,ig_800010,instagram,2025-08-20T15:19:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,985,1296,#StartupEcosystem;#FinancialInclusion,https://instagram.com/p/ig_800010
3,ig_800013,instagram,2025-07-23T12:27:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,6364,1255,#WomenInSTEM;#DigitalLiteracy,https://instagram.com/p/ig_800013
4,ig_800023,instagram,2025-08-01T01:55:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,10700,588,#Sustainability;#PublicHealth,https://instagram.com/p/ig_800023
...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,ig_800993,instagram,2025-07-27T18:02:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,8009,1088,#YouthVoices;#Sustainability,https://instagram.com/p/ig_800993
305,ig_800994,instagram,2025-08-09T21:33:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,9237,783,#Innovation;#SkillDevelopment,https://instagram.com/p/ig_800994
306,ig_800995,instagram,2025-08-17T17:52:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,10328,786,#CommunityDevelopment;#FinancialInclusion,https://instagram.com/p/ig_800995
307,ig_800997,instagram,2025-08-24T20:46:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,4060,948,#CivicEngagement;#Innovation,https://instagram.com/p/ig_800997
308,ig_800998,instagram,2025-08-14T17:41:00Z,en,Proud of initiatives driving progress in India—great energy!,India,pro,safe,False,8893,990,#Innovation;#FinancialInclusion,https://instagram.com/p/ig_800998

In [80]:
df.describe()

              likes     comments
count    309.000000   309.000000
mean   10200.760518   733.495146
std     5457.905844   429.183638
min       45.000000     1.000000
25%     6058.000000   368.000000
50%    10511.000000   759.000000
75%    14379.000000  1073.000000
max    19988.000000  1499.000000